version: "3"

services:
  db:
    image: postgres:12
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ksp
      - POSTGRES_USER=ksp
      - POSTGRES_PASSWORD=ksp
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  data:
