# Generated by Django 4.1.7 on 2023-03-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='employee')),
                ('job', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('status', models.CharField(choices=[('enable', 'Enable'), ('disabled', 'Disabled')], default='enable', max_length=10)),
                ('date_hire', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('brother', 'Brother'), ('grandson', 'Grandson'), ('grandfather', 'Grandfather')], default='father', max_length=12)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('man', 'Man'), ('women', 'Women')], default='man', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
